<#
.SYNOPSIS
    Regenerates Code/V2/Application/ConfusableMappings.g.cs from the Unicode UTS #39
    confusables data.

.DESCRIPTION
    The generated file is committed, so CI's clean-generated-file gate proves the checked-in
    table matches this script's output. The source data is pinned by version AND by SHA-256:
    a silently republished upstream file fails the hash check rather than quietly changing
    who is allowed to impersonate whom.

    The 722 KB source file is deliberately NOT committed. It is fetched on demand and
    verified, or supplied locally with -SourceFile for an offline run.
#>
[CmdletBinding()]
param(
    [Parameter()][string] $SourceFile,
    [Parameter()][switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$UnicodeVersion = '16.0.0'
$SourceUrl = "https://www.unicode.org/Public/security/$UnicodeVersion/confusables.txt"
$SourceSha256 = '95BD0AAD6DCED5EBC63436F459C06AB21A8D107CD842FB57F5C3A1E91BCA8611'

$root = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $root 'Code/V2/Application/ConfusableMappings.g.cs'

if (-not $SourceFile) {
    $SourceFile = Join-Path ([IO.Path]::GetTempPath()) "confusables-$UnicodeVersion.txt"
    if (-not (Test-Path $SourceFile)) {
        Write-Host "==> Fetching $SourceUrl" -ForegroundColor Cyan
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri $SourceUrl -OutFile $SourceFile -UseBasicParsing -TimeoutSec 120
    }
}

$actualSha = (Get-FileHash $SourceFile -Algorithm SHA256).Hash
if ($actualSha -ne $SourceSha256) {
    throw "Confusables source hash mismatch. Expected $SourceSha256, got $actualSha. " +
        "The upstream file changed; review the diff before repinning."
}

# Format: <source> ; <target...> ; MA # comment. Sources are always one code point.
$pattern = [regex]'^([0-9A-F]{4,6})\s*;\s*([0-9A-F]{4,6}(?:\s+[0-9A-F]{4,6})*)\s*;\s*MA\b'
# A List of pairs rather than a dictionary keyed by int: PowerShell binds an integer index on
# OrderedDictionary to the positional indexer, not the key, which silently reads the wrong row.
$parsed = [Collections.Generic.List[object]]::new()
$seen = [Collections.Generic.HashSet[int]]::new()
foreach ($line in [IO.File]::ReadLines($SourceFile)) {
    $match = $pattern.Match($line)
    if (-not $match.Success) { continue }
    $source = [Convert]::ToInt32($match.Groups[1].Value, 16)
    if (-not $seen.Add($source)) { throw ("Duplicate confusable source U+{0:X4}." -f $source) }
    $parsed.Add([pscustomobject]@{
        Source = $source
        Target = @($match.Groups[2].Value -split '\s+' | ForEach-Object { [Convert]::ToInt32($_, 16) })
    })
}
if ($parsed.Count -eq 0) { throw 'No MA mappings were parsed; the source format changed.' }

$sorted = $parsed | Sort-Object Source
$sources = [Collections.Generic.List[int]]::new()
$replacements = [Collections.Generic.List[int]]::new()
$sequences = [Collections.Generic.List[string]]::new()

function Format-Escaped {
    param([int[]] $CodePoints)
    ($CodePoints | ForEach-Object {
        if ($_ -gt 0xFFFF) { '\U{0:X8}' -f $_ } else { '\u{0:X4}' -f $_ }
    }) -join ''
}

foreach ($entry in $sorted) {
    $target = $entry.Target
    $sources.Add($entry.Source)
    if ($target.Count -eq 1) {
        $replacements.Add($target[0])
    }
    else {
        # Negative marks "look in Sequences"; the complement keeps index 0 addressable.
        $replacements.Add(-bnot $sequences.Count)
        $sequences.Add((Format-Escaped -CodePoints $target))
    }
}

function Join-Wrapped {
    param([string[]] $Values, [int] $PerLine)
    $lines = [Collections.Generic.List[string]]::new()
    for ($index = 0; $index -lt $Values.Count; $index += $PerLine) {
        $slice = $Values[$index..([Math]::Min($index + $PerLine - 1, $Values.Count - 1))]
        $lines.Add("`t`t" + ($slice -join ', ') + ',')
    }
    return ($lines -join "`n")
}

$sourceLiterals = $sources | ForEach-Object { '0x{0:X}' -f $_ }
$replacementLiterals = $replacements | ForEach-Object { if ($_ -lt 0) { "$_" } else { '0x{0:X}' -f $_ } }
$sequenceLiterals = $sequences | ForEach-Object { '"' + $_ + '"' }

$header = @"
// <auto-generated>
//     Generated by tools/generate-confusables.ps1 from the Unicode UTS #39 confusables data.
//     Unicode version: $UnicodeVersion
//     Source:          $SourceUrl
//     Source SHA-256:  $SourceSha256
//     DO NOT EDIT BY HAND. Rerun the generator instead; CI fails on an out-of-date file.
// </auto-generated>

#nullable enable

using System;

namespace Hexagon.V2.Application;

/// <summary>
/// The Unicode UTS #39 confusables table: for each code point that is drawn like something
/// else, the prototype it should be compared as. <see cref="CharacterNameSkeleton"/> uses it
/// to decide whether two character names would read as the same name.
/// </summary>
internal static class ConfusableMappings
{
	// static readonly, not const: a const would be folded into the caller at compile time, so
	// the pinning test would compare a literal with itself instead of reading the built table.
	public static readonly string UnicodeVersion = "$UnicodeVersion";
	public static readonly string SourceSha256 = "$SourceSha256";
	public static readonly int EntryCount = $($sources.Count);

	/// <summary>Confusable code points, ascending, searched by <see cref="Array.BinarySearch{T}(T[],T)"/>.</summary>
	private static readonly int[] Sources =
	{
$(Join-Wrapped -Values $sourceLiterals -PerLine 12)
	};

	/// <summary>
	/// Parallel to <see cref="Sources"/>. A non-negative value is the replacement code point;
	/// a negative value is the bitwise complement of an index into <see cref="Sequences"/>.
	/// </summary>
	private static readonly int[] Replacements =
	{
$(Join-Wrapped -Values $replacementLiterals -PerLine 12)
	};

	/// <summary>Replacements that are more than one code point long.</summary>
	private static readonly string[] Sequences =
	{
$(Join-Wrapped -Values $sequenceLiterals -PerLine 6)
	};

	/// <summary>
	/// The prototype for <paramref name="codePoint"/>, or false when it is not confusable
	/// with anything and should be kept as it is.
	/// </summary>
	public static bool TryMap( int codePoint, out int single, out string? sequence )
	{
		var index = Array.BinarySearch( Sources, codePoint );
		if ( index < 0 )
		{
			single = 0;
			sequence = null;
			return false;
		}

		var replacement = Replacements[index];
		if ( replacement < 0 )
		{
			single = 0;
			sequence = Sequences[~replacement];
			return true;
		}

		single = replacement;
		sequence = null;
		return true;
	}
}
"@

$header = $header.Replace("`r`n", "`n")
if ($Check) {
    $existing = if (Test-Path $outputPath) { [IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n") } else { '' }
    if ($existing -ne $header) { throw "'$outputPath' is out of date; rerun tools/generate-confusables.ps1." }
    Write-Host "Confusable table is up to date ($($sources.Count) entries, Unicode $UnicodeVersion)." -ForegroundColor Green
    return
}

[IO.File]::WriteAllText($outputPath, $header, (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote $outputPath ($($sources.Count) entries, $($sequences.Count) sequences, Unicode $UnicodeVersion)." -ForegroundColor Green