namespace Hexagon.Characters;

/// <summary>
/// Base class for character data. Schema devs extend this with [CharVar] properties
/// to define their character fields.
///
/// Usage:
///   public class MyCharacter : HexCharacterData
///   {
///       [CharVar(Default = "John Doe", MinLength = 3, MaxLength = 64, Order = 1,
///                SyncTarget = CharSyncTarget.CharacterName)]
///       public string Name { get; set; }
///
///       [CharVar(Default = "A mysterious stranger.", MinLength = 16, MaxLength = 512, Order = 2,
///                SyncTarget = CharSyncTarget.CharacterDescription)]
///       public string Description { get; set; }
///
///       [CharVar(Order = 3, SyncTarget = CharSyncTarget.CharacterModel)]
///       public string Model { get; set; }
///
///       [CharVar(Local = true)]
///       public int Money { get; set; }
///   }
///
/// The framework auto-discovers the concrete subclass at startup and uses it
/// for all character creation, persistence, and networking.
/// </summary>
public abstract class HexCharacterData
{
	/// <summary>
	/// Unique character ID (generated by the framework).
	/// </summary>
	public string Id { get; set; }

	/// <summary>
	/// Steam ID of the player who owns this character.
	/// </summary>
	public ulong SteamId { get; set; }

	/// <summary>
	/// Character slot index (0-based) for this player.
	/// </summary>
	public int Slot { get; set; }

	/// <summary>
	/// The faction this character belongs to (references FactionDefinition name).
	/// </summary>
	public string Faction { get; set; }

	/// <summary>
	/// The class within the faction (references ClassDefinition name). Empty if no class.
	/// </summary>
	public string Class { get; set; }

	/// <summary>
	/// Permission flags assigned to this character (e.g. "a" = admin, "s" = superadmin).
	/// </summary>
	public HashSet<string> Flags { get; set; } = new();

	/// <summary>
	/// Character IDs this character has been introduced to and can recognize by name.
	/// </summary>
	public HashSet<string> RecognizedIds { get; set; } = new();

	/// <summary>
	/// Base attribute values keyed by attribute ID.
	/// </summary>
	public Dictionary<string, float> AttributeValues { get; set; } = new();

	/// <summary>
	/// Active attribute boosts (temporary and permanent modifiers).
	/// </summary>
	public List<Attributes.AttributeBoost> Boosts { get; set; } = new();

	/// <summary>
	/// When this character was created.
	/// </summary>
	public DateTime CreatedAt { get; set; }

	/// <summary>
	/// When this character was last played.
	/// </summary>
	public DateTime LastPlayedAt { get; set; }

	/// <summary>
	/// Whether this character is currently banned.
	/// </summary>
	public bool IsBanned { get; set; }

	/// <summary>
	/// When the ban expires (null = permanent).
	/// </summary>
	public DateTime? BanExpiry { get; set; }
}

/// <summary>
/// Metadata about a character variable, discovered via sbox TypeLibrary at startup.
/// </summary>
public class CharVarInfo
{
	public string Name { get; set; }
	public Type PropertyType { get; set; }
	public CharVarAttribute Attribute { get; set; }
	public PropertyDescription Property { get; set; }

	public object GetValue( HexCharacterData data ) => Property.GetValue( data );
	public void SetValue( HexCharacterData data, object value ) => Property.SetValue( data, value );
}
